[package]
name = "amice-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
ctor = "0.5.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
lazy_static = "1.5"